name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Yarn Install
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build:prod
        env:
          RELEASE: true

      # - name: Deploy
      #   run: ?
