name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Yarn Install
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          RELEASE: true

      # - name: Deploy
      #   run: netlify deploy --dir dist --prod --message "Deployment of $GITHUB_REF"
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
