name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Yarn Install
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build:prod

      - name: ESLint
        run: yarn test:eslint

      - name: Jest
        run: yarn test:jest

      - name: E2E Tests
        run: yarn test:ci
