name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  # e2e:
  #   name: E2E Tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/cache@v2
  #       id: cache
  #       with:
  #         key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
  #         path: '**/node_modules'

  #     - name: Install Dependencies
  #       if: steps.cache.outputs.cache-hit != 'true'
  #       run: yarn --frozen-lockfile

  #     - name: Build
  #       run: yarn build

  #     - name: E2E Tests
  #       run: yarn e2e

  components:
    name: Component Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright
        run: pnpm dlx playwright install --with-deps

      - name: Run your tests
        run: npm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report

  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: ESLint
        run: yarn test:eslint

  typecheck:
    name: Type Checking
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm test:typecheck
